Repository TeamInterject/BillChop, pull requests merged in 2020-11, with the labels that each got.

#18 Frontend tests
  .github/workflows/frontend.yml
  billchop-fe/.eslintrc.js
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/App.test.tsx
  billchop-fe/src/tests/components/Sidebar.test.tsx
  billchop-fe/tsconfig.json
Labels: enhancement

#22 Added Bill and Loan filtering by time and fixed User and Bill creation.
  billchop-be/BillChopBETests/Services/BillServiceTests.cs
  billchop-be/billchop-be/Controllers/BillsController.cs
  billchop-be/billchop-be/Controllers/LoansController.cs
  billchop-be/billchop-be/DataAccessLayer/Filters/BillDbFilter.cs
  billchop-be/billchop-be/DataAccessLayer/Filters/Factories/BillDbFilterFactory.cs
  billchop-be/billchop-be/DataAccessLayer/Filters/LoanDbFilter.cs
  billchop-be/billchop-be/Services/BillService.cs
  billchop-be/billchop-be/Services/LoanService.cs
  billchop-be/billchop-be/Services/Models/CreateNewBill.cs
  billchop-be/billchop-be/Services/Models/CreateNewUser.cs
  billchop-be/billchop-be/Startup.cs
Labels: enhancement

#25 Feat/search for users
  billchop-be/billchop-be/Controllers/UsersController.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IUserRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/UserEFRepository.cs
  billchop-be/billchop-be/Services/UserService.cs
Labels: enhancement

#24 Feat/bills list
  billchop-fe/src/api/Bill.ts
  billchop-fe/src/api/Loan.ts
  billchop-fe/src/api/User.ts
  billchop-fe/src/assets/add-bill-icon.svg
  billchop-fe/src/assets/bill-icon.svg
  billchop-fe/src/components/AddBillModal.tsx
  billchop-fe/src/components/BillSplitInput.tsx
  billchop-fe/src/components/BillsListAccordion.tsx
  billchop-fe/src/components/GroupPageHeader.tsx
  billchop-fe/src/components/GroupTable.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/pages/GroupsPage.tsx
  billchop-fe/src/styles/index.css
  billchop-fe/src/util/Dictionary.ts
Labels: enhancement

#26 Backend Clients for Frontend
  billchop-fe/.eslintrc.js
  billchop-fe/.vscode/settings.json
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/backend/ServerConfig.ts
  billchop-fe/src/backend/clients/AbstractClient.ts
  billchop-fe/src/backend/clients/BillClient.ts
  billchop-fe/src/backend/clients/GroupClient.ts
  billchop-fe/src/backend/clients/LoanClient.ts
  billchop-fe/src/backend/clients/UserClient.ts
  billchop-fe/src/backend/models/Bill.ts
  billchop-fe/src/backend/models/CreateNewBill.ts
  billchop-fe/src/backend/models/CreateNewGroup.ts
  billchop-fe/src/backend/models/CreateNewUser.ts
  billchop-fe/src/backend/models/Group.ts
  billchop-fe/src/backend/models/Loan.ts
  billchop-fe/src/backend/models/LoginDetails.ts
  billchop-fe/src/backend/models/User.ts
  billchop-fe/src/backend/server-config.json
  billchop-fe/src/components/BillsListAccordion.tsx
  billchop-fe/src/components/GroupTable.tsx
  billchop-fe/src/pages/CreateGroupPage.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/pages/GroupsPage.tsx
Labels: enhancement

#27 API calls to Client Calls
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/backend/helpers/UserContext.ts
  billchop-fe/src/backend/models/User.ts
  billchop-fe/src/pages/CreateGroupPage.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/pages/GroupsPage.tsx
Labels: enhancement

#28 Feat/spending chart
  .gitignore
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/backend/models/Bill.ts
  billchop-fe/src/components/BarChart.tsx
  billchop-fe/src/components/GroupPageHeader.tsx
  billchop-fe/src/components/ImageButton.tsx
  billchop-fe/src/components/NavigationBar.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/util/Months.ts
Labels: enhancement

#29 Ability to Login
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/App.tsx
  billchop-fe/src/PrivateRoute.tsx
  billchop-fe/src/backend/ServerConfig.ts
  billchop-fe/src/backend/helpers/History.ts
  billchop-fe/src/backend/helpers/UserContext.ts
  billchop-fe/src/backend/server-config.json
  billchop-fe/src/components/NavigationBar.tsx
  billchop-fe/src/pages/CreateGroupPage.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/pages/GroupsPage.tsx
  billchop-fe/src/pages/LoginPage.scss
  billchop-fe/src/pages/LoginPage.tsx
  billchop-fe/src/styles/group-page.css
  billchop-fe/src/styles/index.css
Labels: enhancement

#30 Added showing colored loaned and owned amounts
  billchop-be/billchop-be/DataAccessLayer/Models/Loan.cs
  billchop-fe/.eslintrc.js
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/backend/models/Loan.ts
  billchop-fe/src/components/GroupTable.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/tests/components/Sidebar.test.tsx
Labels: enhancement

#31 Turned no-unused-vars back on
  billchop-fe/.eslintrc.js
Labels: hotfix

#32 Multi Name Bugfix
  billchop-fe/src/pages/GroupsPage.tsx
Labels: enhancement

#34 Replaced prettier with custom eslint rules
  billchop-fe/.eslintrc.js
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/App.tsx
  billchop-fe/src/backend/clients/AbstractClient.ts
  billchop-fe/src/backend/clients/BillClient.ts
  billchop-fe/src/backend/clients/GroupClient.ts
  billchop-fe/src/backend/clients/LoanClient.ts
  billchop-fe/src/backend/clients/UserClient.ts
  billchop-fe/src/components/GroupTable.tsx
  billchop-fe/src/index.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/pages/GroupsPage.tsx
  billchop-fe/src/serviceWorker.ts
  billchop-fe/src/tests/components/Sidebar.test.tsx
Labels: hotfix

#33 Feat/registration
  billchop-fe/src/App.tsx
  billchop-fe/src/backend/helpers/UserContext.ts
  billchop-fe/src/pages/LoginPage.scss
  billchop-fe/src/pages/LoginPage.tsx
  billchop-fe/src/pages/RegistrationPage.tsx
  billchop-fe/src/styles/index.css
Labels: enhancement

#35 Fixed search users type
  billchop-be/billchop-be/Controllers/UsersController.cs
Labels: hotfix

#37 Added exclusion group to search endpoint
  billchop-be/billchop-be/Controllers/UsersController.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IUserRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/UserEFRepository.cs
  billchop-be/billchop-be/Services/UserService.cs
  billchop-fe/src/backend/clients/UserClient.ts
Labels: hotfix

#36 Feat/search box
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/assets/add-person-icon.svg
  billchop-fe/src/assets/arrow-back-icon.svg
  billchop-fe/src/assets/search-icon.svg
  billchop-fe/src/backend/ServerConfig.ts
  billchop-fe/src/backend/server-config.json
  billchop-fe/src/components/GroupPageHeader.tsx
  billchop-fe/src/components/GroupTable.tsx
  billchop-fe/src/components/OutsideClickListener.tsx
  billchop-fe/src/components/SearchBox.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/pages/GroupsPage.tsx
  billchop-fe/src/styles/search-box.css
Labels: enhancement

#38 Normalized launch configs
  billchop-be/billchop-be/Properties/launchSettings.json
  billchop-fe/src/backend/server-config.json
Labels: enhancement

#39 bug/accordion-icon-not-clickable
  billchop-fe/src/components/BillsListAccordion.tsx
Labels: bug

#40 Feat/bill totals
  billchop-fe/src/components/BillsListAccordion.tsx
Labels: enhancement

#41 Marked script as bash
  git_delete_removed_branches.sh
Labels: hotfix

#43 Refactor/css to bootstrap grid layout
  billchop-fe/public/index.html
  billchop-fe/src/App.tsx
  billchop-fe/src/components/AddBillModal.tsx
  billchop-fe/src/components/GroupPageHeader.tsx
  billchop-fe/src/components/ImageButton.tsx
  billchop-fe/src/components/NavigationBar.tsx
  billchop-fe/src/components/Sidebar.tsx
  billchop-fe/src/pages/CreateGroupPage.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/pages/GroupsPage.tsx
  billchop-fe/src/pages/NoGroupSelectedSubPage.tsx
  billchop-fe/src/styles/create-group-page.css
  billchop-fe/src/styles/group-page.css
  billchop-fe/src/styles/groups-page.css
  billchop-fe/src/styles/index.css
Labels: enhancement

#44 Feat/progress bar
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/App.tsx
  billchop-fe/src/backend/clients/BillClient.ts
  billchop-fe/src/backend/clients/GroupClient.ts
  billchop-fe/src/backend/clients/LoanClient.ts
  billchop-fe/src/backend/clients/UserClient.ts
  billchop-fe/src/backend/helpers/LoadingContext.ts
  billchop-fe/src/components/BarChart.tsx
  billchop-fe/src/components/LoadingSpinner.tsx
  billchop-fe/src/components/SearchBox.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/styles/bill-list-accordion.css
  billchop-fe/src/styles/index.css
  billchop-fe/src/styles/loading-spinner.css
  billchop-fe/src/styles/search-box.css
Labels: enhancement

#48 Bug/user email search
  billchop-be/billchop-be/DataAccessLayer/Repositories/UserEFRepository.cs
Labels: bug

#49 Fixed problem where sort was trying to sort immutable array
  billchop-fe/src/components/GroupTable.tsx
Labels: bug, hotfix

#52 Added bill dates and bill sorting by creation date
  billchop-fe/src/components/BillsListAccordion.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
Labels: enhancement

#56 Feat/test user group
  billchop-be/BillChopBETests/Services/GroupServiceTests.cs
  billchop-be/BillChopBETests/Services/UserServiceTests.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IUserRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/UserEFRepository.cs
  billchop-be/billchop-be/Services/Models/LoginDetails.cs
  billchop-be/billchop-be/Services/UserService.cs
Labels: tests

#60 Upgrade to .NET 5
  .github/workflows/backend.yml
  billchop-be/BillChopBETests/BillChopBETests.csproj
  billchop-be/ProjectPortableTools/ProjectPortableTools.csproj
  billchop-be/billchop-be/BillChopBE.csproj
  billchop-be/billchop-be/Startup.cs
Labels: enhancement

#58 Feat/code cov fe
  .github/workflows/backend.yml
  .github/workflows/coverage.yml
  billchop-be/BillChopBETests/BillChopBETests.csproj
  billchop-fe/.gitignore
  billchop-fe/.nycrc.json
  billchop-fe/package-lock.json
  billchop-fe/package.json
  lcov-merger/.gitignore
  lcov-merger/package-lock.json
  lcov-merger/package.json
  scripts/create-docker-db.sh
  scripts/git_delete_removed_branches.sh
Labels: tests

#62 Hotfix master not building everytime
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: enhancement

#63 Fixing backend code smell issues
  .github/workflows/backend.yml
  billchop-be/BillChopBETests/Services/BillServiceTests.cs
  billchop-be/BillChopBETests/Services/GroupServiceTests.cs
  billchop-be/BillChopBETests/Services/UserServiceTests.cs
  billchop-be/ProjectPortableTools/Extensions/DecimalExtensions.cs
  billchop-be/ProjectPortableTools/Extensions/IntExtensions.cs
  billchop-be/billchop-be/Controllers/UsersController.cs
  billchop-be/billchop-be/DataAccessLayer/BillChopContext.cs
  billchop-be/billchop-be/DataAccessLayer/ConnectionStringResolver.cs
  billchop-be/billchop-be/DataAccessLayer/Filters/AbstractDbFilter.cs
  billchop-be/billchop-be/DataAccessLayer/Filters/Factories/BillDbFilterFactory.cs
  billchop-be/billchop-be/DataAccessLayer/Filters/Factories/LoanDbFilterFactory.cs
  billchop-be/billchop-be/DataAccessLayer/Models/Interfaces/IDbModel.cs
  billchop-be/billchop-be/DataAccessLayer/Models/Loan.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/AbstractEFRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/GroupEFRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IBillRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/ILoanRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/LoanEFRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/UserEFRepository.cs
  billchop-be/billchop-be/Exceptions/AbstractUserFriendlyException.cs
  billchop-be/billchop-be/Exceptions/BadRequestException.cs
  billchop-be/billchop-be/Exceptions/DbException.cs
  billchop-be/billchop-be/Exceptions/HttpException.cs
  billchop-be/billchop-be/Exceptions/NotFoundException.cs
  billchop-be/billchop-be/Exceptions/UnauthorizedException.cs
  billchop-be/billchop-be/Middleware/TransactionMiddleware.cs
  billchop-be/billchop-be/Program.cs
  billchop-be/billchop-be/Services/BillService.cs
  billchop-be/billchop-be/Services/Configurations/JwtConfig.cs
  billchop-be/billchop-be/Services/GroupService.cs
  billchop-be/billchop-be/Services/Hasher.cs
  billchop-be/billchop-be/Services/Models/CreateNewBill.cs
  billchop-be/billchop-be/Services/Models/CreateNewGroup.cs
  billchop-be/billchop-be/Services/Models/CreateNewUser.cs
  billchop-be/billchop-be/Services/Models/LoginDetails.cs
  billchop-be/billchop-be/Services/UserService.cs
  billchop-be/billchop-be/Startup.cs
Labels: enhancement
