Repository TeamInterject/BillChop, pull requests merged in 2020-10, with the labels that each got.

#2 Eslint
  billchop-fe/billchop/.eslintrc.js
  billchop-fe/billchop/package-lock.json
  billchop-fe/billchop/package.json
  billchop-fe/billchop/src/App.test.tsx
  billchop-fe/billchop/src/App.tsx
  billchop-fe/billchop/src/index.tsx
  billchop-fe/billchop/src/serviceWorker.ts
  billchop-fe/billchop/src/setupTests.ts
Labels: enhancement

#3 Moved folder structure up
  .github/workflows/frontend.yml
  billchop-fe/.eslintrc.js
  billchop-fe/.gitignore
  billchop-fe/README.md
  billchop-fe/billchop/package-lock.json
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/public/favicon.ico
  billchop-fe/public/index.html
  billchop-fe/public/logo192.png
  billchop-fe/public/logo512.png
  billchop-fe/public/manifest.json
  billchop-fe/public/robots.txt
  billchop-fe/src/App.css
  billchop-fe/src/App.test.tsx
  billchop-fe/src/App.tsx
  billchop-fe/src/index.css
  billchop-fe/src/index.tsx
  billchop-fe/src/logo.svg
  billchop-fe/src/react-app-env.d.ts
  billchop-fe/src/serviceWorker.ts
  billchop-fe/src/setupTests.ts
  billchop-fe/tsconfig.json
Labels: hotfix

#4 Created new backend project
  billchop-be/.gitignore
  billchop-be/billchop-be.sln
  billchop-be/billchop-be/Controllers/WeatherForecastController.cs
  billchop-be/billchop-be/Program.cs
  billchop-be/billchop-be/Properties/launchSettings.json
  billchop-be/billchop-be/Startup.cs
  billchop-be/billchop-be/WeatherForecast.cs
  billchop-be/billchop-be/appsettings.json
  billchop-be/billchop-be/billchop-be.csproj
Labels: enhancement

#6 Feat/db setup
  billchop-be/billchop-be.sln
  billchop-be/billchop-be/BillChopBE.csproj
  billchop-be/billchop-be/Controllers/UsersController.cs
  billchop-be/billchop-be/Controllers/WeatherForecastController.cs
  billchop-be/billchop-be/DataAccessLayer/BillChopContext.cs
  billchop-be/billchop-be/DataAccessLayer/ConnectionStringResolver.cs
  billchop-be/billchop-be/DataAccessLayer/Models/Bill.cs
  billchop-be/billchop-be/DataAccessLayer/Models/Expense.cs
  billchop-be/billchop-be/DataAccessLayer/Models/Group.cs
  billchop-be/billchop-be/DataAccessLayer/Models/Interfaces/IDbModel.cs
  billchop-be/billchop-be/DataAccessLayer/Models/User.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/AbstractEFRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/BillEFRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/ExpenseEFRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/GroupEFRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IBillRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IExpenseRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IGroupRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/Interfaces/IUserRepository.cs
  billchop-be/billchop-be/DataAccessLayer/Repositories/UserEFRepository.cs
  billchop-be/billchop-be/Exceptions/AbstractUserFriendlyException.cs
  billchop-be/billchop-be/Exceptions/BadRequestException.cs
  billchop-be/billchop-be/Exceptions/DbException.cs
  billchop-be/billchop-be/Exceptions/HttpException.cs
  billchop-be/billchop-be/Exceptions/NotFoundException.cs
  billchop-be/billchop-be/Extensions/BillChopContextExtensions.cs
  billchop-be/billchop-be/Extensions/WebHostExtensions.cs
  billchop-be/billchop-be/Middleware/ErrorHandlingMiddleware.cs
  billchop-be/billchop-be/Middleware/TransactionMiddleware.cs
  billchop-be/billchop-be/Migrations/20201017122212_InitialMigration.Designer.cs
  billchop-be/billchop-be/Migrations/20201017122212_InitialMigration.cs
  billchop-be/billchop-be/Migrations/20201019192423_Relationships.Designer.cs
  billchop-be/billchop-be/Migrations/20201019192423_Relationships.cs
  billchop-be/billchop-be/Migrations/BillChopContextModelSnapshot.cs
  billchop-be/billchop-be/Program.cs
  billchop-be/billchop-be/Properties/launchSettings.json
  billchop-be/billchop-be/Services/Models/CreateNewUser.cs
  billchop-be/billchop-be/Services/UserService.cs
  billchop-be/billchop-be/Startup.cs
  billchop-be/billchop-be/Validation/ValidatableModel.cs
  billchop-be/billchop-be/WeatherForecast.cs
  billchop-be/billchop-be/appsettings.json
  billchop-be/billchop-be/billchop-be.csproj
Labels: enhancement

#8 Added script for deleting branches that were deleted in remote
  git_delete_removed_branches.sh
Labels: dev tools

#10 Added swagger
  billchop-be/billchop-be/BillChopBE.csproj
  billchop-be/billchop-be/Properties/launchSettings.json
  billchop-be/billchop-be/Startup.cs
Labels: enhancement

#14 Fixed bug where loan history was not loaded
  billchop-fe/src/api/User.ts
  billchop-fe/src/components/GroupTable.tsx
Labels: enhancement
