Repository TeamInterject/BillChop, pull requests merged in 2020-12, with the labels that each got.

#65 Feat/settle-up-fe
  billchop-fe/src/assets/settle-up-icon.svg
  billchop-fe/src/components/CurrencyInput.tsx
  billchop-fe/src/components/GroupPageHeader.tsx
  billchop-fe/src/components/SettleUpSlider.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
  billchop-fe/src/pages/GroupsPage.tsx
  billchop-fe/src/pages/SettleUpSubPage.tsx
  billchop-fe/src/styles/currency-input.css
  billchop-fe/src/styles/groups-page.css
Labels: enhancement

#69 Excluded migrations from coverage
  .github/workflows/coverage.yml
Labels: hotfix

#75 Hotfix/group table depends on user context
  billchop-fe/src/backend/clients/PaymentClient.ts
  billchop-fe/src/components/BillsListAccordion.tsx
  billchop-fe/src/components/GroupTable.tsx
  billchop-fe/src/pages/GroupSubPage.tsx
Labels: hotfix

#78 Update README.md
  README.md
Labels: enhancement

#76 Payment service tests
  billchop-be/BillChopBETests/Services/PaymentServiceTests.cs
  billchop-be/billchop-be/Services/Models/CreateNewPayment.cs
  billchop-be/billchop-be/Services/PaymentService.cs
Labels: tests

#77 Group Table Tests
  billchop-fe/src/components/GroupTable.tsx
  billchop-fe/src/tests/components/GroupTable.test.tsx
Labels: tests

#71 Backend Service and Data Layer Tests
  billchop-be/BillChopBETests/DataAccessLayer/Filters/BillDbFilterTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Filters/Factories/BillDbFilterFactoryTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Filters/Factories/LoanDbFilterFactoryTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Filters/Factories/PaymentDbFilterFactoryTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Filters/LoanDbFilterTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Filters/PaymentDbFilterTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Models/BillTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Models/GroupTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Models/LoanTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Models/PaymentTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Models/UserTests.cs
  billchop-be/BillChopBETests/DataAccessLayer/Models/UserWithTokenTests.cs
  billchop-be/BillChopBETests/Services/BillServiceTests.cs
  billchop-be/BillChopBETests/Services/GroupServiceTests.cs
  billchop-be/BillChopBETests/Services/LoansServiceTests.cs
  billchop-be/BillChopBETests/Services/UserServiceTests.cs
  billchop-be/ProjectPortableTools/Extensions/DecimalExtensions.cs
  billchop-be/ProjectPortableTools/Extensions/IntExtensions.cs
  billchop-be/billchop-be/DataAccessLayer/Filters/BillDbFilter.cs
  billchop-be/billchop-be/Extensions/ServiceCollectionAutoMapperExtensions.cs
  billchop-be/billchop-be/Services/GroupService.cs
  billchop-be/billchop-be/Services/Models/UserWithToken.cs
  billchop-be/billchop-be/Services/Models/UserWithoutPassword.cs
  billchop-be/billchop-be/Services/UserService.cs
Labels: tests

#79 JS floating numbers quirks hotfix
  billchop-fe/package-lock.json
  billchop-fe/package.json
  billchop-fe/src/pages/GroupSubPage.tsx
Labels: hotfix

#80 Hotfix/remove untestable code from cov
  .github/workflows/coverage.yml
  billchop-be/billchop-be/Validation/ValidatableModel.cs
  billchop-fe/.nycrc.json
Labels: hotfix, tests
